/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.12.v201805221014.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_MEDIAPLAYER_MEDIA_PLAYER_HPP_
#define V1_MEDIAPLAYER_MEDIA_PLAYER_HPP_




#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/Types.hpp>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1 {
namespace MediaPlayer {

class MediaPlayer {
public:
    virtual ~MediaPlayer() { }

    static inline const char* getInterface();
    static inline CommonAPI::Version getInterfaceVersion();
};

const char* MediaPlayer::getInterface() {
    return ("MediaPlayer.MediaPlayer:v1_0");
}

CommonAPI::Version MediaPlayer::getInterfaceVersion() {
    return CommonAPI::Version(1, 0);
}


} // namespace MediaPlayer
} // namespace v1

namespace CommonAPI {
}


// Compatibility
namespace v1_0 = v1;

#endif // V1_MEDIAPLAYER_MEDIA_PLAYER_HPP_
