/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.dbus 3.1.12.v201801251438.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#include "MediaPlayerTypesDBusDeployment.hpp"

namespace v1 {
namespace MediaPlayer {
namespace MediaPlayerTypes_ {

// typecollection-specific deployments

} // namespace MediaPlayerTypes_
} // namespace MediaPlayer
} // namespace v1
