/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.dbus 3.1.12.v201801251438.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#include <v1/MediaPlayer/MediaPlayer.hpp>
#include <v1/MediaPlayer/MediaPlayerDBusStubAdapter.hpp>

namespace v1 {
namespace MediaPlayer {

std::shared_ptr<CommonAPI::DBus::DBusStubAdapter> createMediaPlayerDBusStubAdapter(
                   const CommonAPI::DBus::DBusAddress &_address,
                   const std::shared_ptr<CommonAPI::DBus::DBusProxyConnection> &_connection,
                   const std::shared_ptr<CommonAPI::StubBase> &_stub) {
    return std::make_shared< MediaPlayerDBusStubAdapter<::v1::MediaPlayer::MediaPlayerStub>>(_address, _connection, std::dynamic_pointer_cast<::v1::MediaPlayer::MediaPlayerStub>(_stub));
}

void initializeMediaPlayerDBusStubAdapter() {
    CommonAPI::DBus::Factory::get()->registerStubAdapterCreateMethod(
        MediaPlayer::getInterface(), &createMediaPlayerDBusStubAdapter);
}

INITIALIZER(registerMediaPlayerDBusStubAdapter) {
    CommonAPI::DBus::Factory::get()->registerInterface(initializeMediaPlayerDBusStubAdapter);
}

} // namespace MediaPlayer
} // namespace v1
