/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.12.v201805221014.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_MEDIAPLAYER_Media_Player_Types_HPP_
#define V1_MEDIAPLAYER_Media_Player_Types_HPP_



#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Types.hpp>
#include <cstdint>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1 {
namespace MediaPlayer {

struct MediaPlayerTypes {
    
    struct CurrentState : CommonAPI::Enumeration< int32_t> {
        enum Literal : int32_t {
            PAUSED = 0,
            PLAYING = 1
        };
    
        CurrentState()
            : CommonAPI::Enumeration< int32_t>(static_cast< int32_t>(Literal::PAUSED)) {}
        CurrentState(Literal _literal)
            : CommonAPI::Enumeration< int32_t>(static_cast< int32_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast< int32_t>(Literal::PAUSED):
                case static_cast< int32_t>(Literal::PLAYING):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const CurrentState &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const CurrentState &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const CurrentState &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const CurrentState &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const CurrentState &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const CurrentState &_other) const { return (value_ > _other.value_); }
    
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast< int32_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast< int32_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast< int32_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast< int32_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast< int32_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast< int32_t>(_value)); }
    };



static inline const char* getTypeCollectionName() {
    static const char* typeCollectionName = "MediaPlayer.MediaPlayerTypes";
    return typeCollectionName;
}

inline CommonAPI::Version getTypeCollectionVersion() {
    return CommonAPI::Version(1, 0);
}

}; // struct MediaPlayerTypes

} // namespace MediaPlayer
} // namespace v1

namespace CommonAPI {
}


namespace std {
    //Hash for CurrentState
    template<>
    struct hash< ::v1::MediaPlayer::MediaPlayerTypes::CurrentState> {
        inline size_t operator()(const ::v1::MediaPlayer::MediaPlayerTypes::CurrentState& currentState) const {
            return static_cast< int32_t>(currentState);
        }
    };
}


// Compatibility
namespace v1_0 = v1;

#endif // V1_MEDIAPLAYER_Media_Player_Types_HPP_
